name: feature-pipeline-backend

on: [push]
permissions:
  contents: read
  statuses: write
  security-events: read

jobs:
  feature-pipeline:
    if: github.ref != 'refs/heads/main'
    uses: tata-actions/workflows/.github/workflows/feature-nodejs-pipeline.yaml@main
    with:
      project: expense-project
      component: backend
      environment: dev
    secrets: inherit  

  dev-pipeline:
    if: github.ref == 'refs/heads/main'
    uses: tata-actions/workflows/.github/workflows/dev-nodejs-pipeline.yaml@main
    with:
      project: expense-projectss
      component: backend
      environment: dev
    secrets: inherit   
